Repository SukiSU-Ultra/SukiSU-Ultra, pull requests merged in 2025-06, with the labels that each got.

#216 Bump agp and Gradle to latest
  .gitignore
  manager/gradle/libs.versions.toml
  manager/gradle/wrapper/gradle-wrapper.jar
  manager/gradle/wrapper/gradle-wrapper.properties
  manager/gradlew
  manager/gradlew.bat
Labels: enhancement

#234 manager: Fix unintended LKM dialog when selecting AnyKernel3 install method
  manager/app/src/main/java/com/sukisu/ultra/ui/screen/Install.kt
Labels: bug

#233 manager: Only display slotinformation on AB devices
  manager/app/src/main/java/com/sukisu/ultra/ui/screen/SuSFSConfig.kt
Labels: enhancement

#229 Update Vietnamese Translation
  manager/app/src/main/res/values-vi/strings.xml
Labels: translate

#240 New Crowdin updates
  manager/app/src/main/res/values-in/strings.xml
  manager/app/src/main/res/values-ja/strings.xml
  manager/app/src/main/res/values-ru/strings.xml
  manager/app/src/main/res/values-tr/strings.xml
  manager/app/src/main/res/values-zh-rHK/strings.xml
  manager/app/src/main/res/values-zh-rTW/strings.xml
Labels: translate
