Repository SukiSU-Ultra/SukiSU-Ultra, pull requests merged in 2025-07, with the labels that each got.

#257 Update Vietnamese Translation
  manager/app/src/main/res/values-vi/strings.xml
Labels: translate

#260 Update Vietnamese Traslation
  manager/app/src/main/res/values-vi/strings.xml
Labels: translate

#268 fix(manager): add extraspace after "UID:" for Home screen
  manager/app/src/main/java/com/sukisu/ultra/ui/screen/Home.kt
Labels: reformat

#270 kernel: core_hook: add support for KernelNoSU
  kernel/core_hook.c
Labels: enhancement

#276 UPSTREAM: manager: improve predictive back animations
  manager/app/build.gradle.kts
  manager/app/src/main/java/com/sukisu/ultra/ui/MainActivity.kt
Labels: enhancement, UPSTREAM

#281 docs: Revamped README and documentation
  docs/README-en.md
  docs/README.md
  docs/guide/how-to-integrate.md
  docs/guide/installation.md
  docs/ja/README.md
  docs/tr/README.md
  docs/zakomonochrome-128.svg
  docs/zh/README.md
  docs/zh/guide/how-to-integrate.md
  docs/zh/guide/installation.md
  docs/zh/zakomonochrome-128.svg
Labels: documentation

#284 Update Vietnamese Translation
  manager/app/src/main/res/values-vi/strings.xml
Labels: translate

#290 readme: add chinese translation
  docs/zh/README.md
  docs/zh/guide/how-to-integrate.md
  docs/zh/guide/installation.md
Labels: documentation

#291 manager: Remove Loading Dialog when enable/disable the module
  manager/app/src/main/java/com/sukisu/ultra/ui/screen/Module.kt
Labels: enhancement
